name: absence_manager
description: "A Flutter application to manage and display employee absences."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Use this command to run the code generator for models:
  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/json/absences.json
    - assets/json/members.json